name: Alpha

on:
  push:
    branches: [ main ]

jobs:
  build-en:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.1.0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Install npm dependencies
        run: pnpm install
      - name: Run build task
        run: pnpm build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --filter=':- .gitignore'
          path: dist/*
          remote_path: /data/kirby-web
          remote_host: 20.212.6.4
          remote_user: why
          remote_key: ${{ secrets.DEPLOY_KEY }}
